nama = input("Nama                 : ")
nim = input("NIM                  : ")
paralel = input("Kelas Paralel        : ")
ttl = input("Tempat/Tanggal Lahir : ")
alamat = input("Alamat               : ")
hobby = input("Hobby                : ")
nomor = input("No. HP               : ")

print(f"\nNama                 : {nama}")
print(f"NIM                  : {nim}")
print(f"Kelas Paralel        : {paralel}")
print(f"Tempat/Tanggal Lahir : {ttl}")
print(f"Alamat               : {alamat}")
print(f"Hobby                : {hobby}")
print(f"No. HP               : {nomor}")